local TowerConfig = {}

TowerConfig.Rarities = { "Common", "Rare", "Epic", "Legendary", "Mythic" }

TowerConfig.RarityOrder = {
	Common = 1,
	Rare = 2,
	Epic = 3,
	Legendary = 4,
	Mythic = 5,
}

TowerConfig.Origins = {
	Astral = { color = Color3.fromRGB(112, 180, 255) },
	Ember = { color = Color3.fromRGB(255, 106, 74) },
	Mech = { color = Color3.fromRGB(170, 184, 196) },
	Wild = { color = Color3.fromRGB(109, 211, 124) },
}

TowerConfig.Classes = {
	Marksman = { role = "single-target damage" },
	Arcanist = { role = "area and burst damage" },
	Guardian = { role = "control and support damage" },
}

TowerConfig.Towers = {
	AstralScout = {
		displayName = "Astral Scout",
		rarity = "Common",
		origin = "Astral",
		class = "Marksman",
		cost = 1,
		damage = 8,
		range = 18,
		cooldown = 0.9,
		visual = "AstralScout",
	},
	AstralAdept = {
		displayName = "Astral Adept",
		rarity = "Common",
		origin = "Astral",
		class = "Arcanist",
		cost = 1,
		damage = 6,
		range = 16,
		cooldown = 1.0,
		splash = 4,
		visual = "AstralAdept",
	},
	AstralWarden = {
		displayName = "Astral Warden",
		rarity = "Rare",
		origin = "Astral",
		class = "Guardian",
		cost = 2,
		damage = 7,
		range = 15,
		cooldown = 1.1,
		slow = 0.12,
		visual = "AstralWarden",
	},
	AstralComet = {
		displayName = "Astral Comet",
		rarity = "Epic",
		origin = "Astral",
		class = "Arcanist",
		cost = 3,
		damage = 15,
		range = 18,
		cooldown = 1.6,
		splash = 7,
		visual = "AstralComet",
	},
	AstralRanger = {
		displayName = "Astral Ranger",
		rarity = "Legendary",
		origin = "Astral",
		class = "Marksman",
		cost = 4,
		damage = 24,
		range = 22,
		cooldown = 0.8,
		visual = "AstralRanger",
	},
	AstralParagon = {
		displayName = "Astral Paragon",
		rarity = "Mythic",
		origin = "Astral",
		class = "Guardian",
		cost = 5,
		damage = 35,
		range = 20,
		cooldown = 1.2,
		slow = 0.22,
		visual = "AstralParagon",
	},
	EmberPiker = {
		displayName = "Ember Piker",
		rarity = "Common",
		origin = "Ember",
		class = "Guardian",
		cost = 1,
		damage = 7,
		range = 14,
		cooldown = 0.95,
		visual = "EmberPiker",
	},
	EmberSpark = {
		displayName = "Ember Spark",
		rarity = "Common",
		origin = "Ember",
		class = "Arcanist",
		cost = 1,
		damage = 5,
		range = 16,
		cooldown = 0.8,
		splash = 3,
		visual = "EmberSpark",
	},
	EmberGunner = {
		displayName = "Ember Gunner",
		rarity = "Rare",
		origin = "Ember",
		class = "Marksman",
		cost = 2,
		damage = 11,
		range = 18,
		cooldown = 0.75,
		visual = "EmberGunner",
	},
	EmberPyre = {
		displayName = "Ember Pyre",
		rarity = "Epic",
		origin = "Ember",
		class = "Arcanist",
		cost = 3,
		damage = 16,
		range = 17,
		cooldown = 1.35,
		splash = 6,
		visual = "EmberPyre",
	},
	EmberBulwark = {
		displayName = "Ember Bulwark",
		rarity = "Legendary",
		origin = "Ember",
		class = "Guardian",
		cost = 4,
		damage = 18,
		range = 16,
		cooldown = 1.0,
		armorShred = 0.16,
		visual = "EmberBulwark",
	},
	EmberPhoenix = {
		displayName = "Ember Phoenix",
		rarity = "Mythic",
		origin = "Ember",
		class = "Marksman",
		cost = 5,
		damage = 40,
		range = 23,
		cooldown = 0.7,
		visual = "EmberPhoenix",
	},
	MechBolt = {
		displayName = "Mech Bolt",
		rarity = "Common",
		origin = "Mech",
		class = "Marksman",
		cost = 1,
		damage = 9,
		range = 17,
		cooldown = 1.0,
		visual = "MechBolt",
	},
	MechRelay = {
		displayName = "Mech Relay",
		rarity = "Common",
		origin = "Mech",
		class = "Guardian",
		cost = 1,
		damage = 4,
		range = 15,
		cooldown = 1.1,
		slow = 0.08,
		visual = "MechRelay",
	},
	MechCaster = {
		displayName = "Mech Caster",
		rarity = "Rare",
		origin = "Mech",
		class = "Arcanist",
		cost = 2,
		damage = 10,
		range = 17,
		cooldown = 1.15,
		splash = 4,
		visual = "MechCaster",
	},
	MechSniper = {
		displayName = "Mech Sniper",
		rarity = "Epic",
		origin = "Mech",
		class = "Marksman",
		cost = 3,
		damage = 25,
		range = 25,
		cooldown = 1.8,
		visual = "MechSniper",
	},
	MechAegis = {
		displayName = "Mech Aegis",
		rarity = "Legendary",
		origin = "Mech",
		class = "Guardian",
		cost = 4,
		damage = 19,
		range = 18,
		cooldown = 1.05,
		armorShred = 0.18,
		visual = "MechAegis",
	},
	MechOracle = {
		displayName = "Mech Oracle",
		rarity = "Mythic",
		origin = "Mech",
		class = "Arcanist",
		cost = 5,
		damage = 38,
		range = 21,
		cooldown = 1.35,
		splash = 8,
		visual = "MechOracle",
	},
	WildThorn = {
		displayName = "Wild Thorn",
		rarity = "Common",
		origin = "Wild",
		class = "Guardian",
		cost = 1,
		damage = 6,
		range = 14,
		cooldown = 0.9,
		slow = 0.08,
		visual = "WildThorn",
	},
	WildSlinger = {
		displayName = "Wild Slinger",
		rarity = "Common",
		origin = "Wild",
		class = "Marksman",
		cost = 1,
		damage = 8,
		range = 18,
		cooldown = 0.85,
		visual = "WildSlinger",
	},
	WildBloom = {
		displayName = "Wild Bloom",
		rarity = "Rare",
		origin = "Wild",
		class = "Arcanist",
		cost = 2,
		damage = 9,
		range = 16,
		cooldown = 1.0,
		splash = 4,
		visual = "WildBloom",
	},
	WildHunter = {
		displayName = "Wild Hunter",
		rarity = "Epic",
		origin = "Wild",
		class = "Marksman",
		cost = 3,
		damage = 18,
		range = 20,
		cooldown = 0.7,
		visual = "WildHunter",
	},
	WildKeeper = {
		displayName = "Wild Keeper",
		rarity = "Legendary",
		origin = "Wild",
		class = "Guardian",
		cost = 4,
		damage = 16,
		range = 18,
		cooldown = 0.95,
		slow = 0.18,
		visual = "WildKeeper",
	},
	WildAvatar = {
		displayName = "Wild Avatar",
		rarity = "Mythic",
		origin = "Wild",
		class = "Arcanist",
		cost = 5,
		damage = 36,
		range = 20,
		cooldown = 1.15,
		splash = 9,
		visual = "WildAvatar",
	},
}

function TowerConfig.GetTowerIdsByRarity(rarity)
	local ids = {}
	for towerId, tower in pairs(TowerConfig.Towers) do
		if tower.rarity == rarity then
			table.insert(ids, towerId)
		end
	end
	table.sort(ids)
	return ids
end

function TowerConfig.GetNextRarity(rarity)
	local index = TowerConfig.RarityOrder[rarity]
	if index == nil then
		return nil
	end

	return TowerConfig.Rarities[math.min(index + 1, #TowerConfig.Rarities)]
end

return TowerConfig
